version: "3.7"

x-opensearch-common: &opensearch-common
  image: opensearchproject/opensearch:2.0.0
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
      hard: 65536
  networks:
    - opensearch-net
  environment: &environment-common
    cluster.name: opensearch-cluster
    discovery.seed_hosts: opensearch-node1,opensearch-node2
    cluster.initial_master_nodes: opensearch-node1,opensearch-node2
    bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
    OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM

services:
  opensearch-node1:
    <<: *opensearch-common
    container_name: opensearch-node1
    environment:
      <<: *environment-common
      node.name: opensearch-node1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer

  opensearch-node2:
    <<: *opensearch-common
    container_name: opensearch-node2
    environment:
      <<: *environment-common
      node.name: opensearch-node2
    volumes:
      - opensearch-data2:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.0.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net: