services:
  neo4j:
    image: neo4j:latest
    container_name: graphdb
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./docker/data:/data
      - ./docker/logs:/logs
      - ./docker/plugins:/plugins
    environment: 
      - NEO4J_server_memory_pagecache_size=516M
      - NEO4J_server_memory_heap_initial__size=516M
      - NEO4J_server_memory_heap_max__size=516M
      # - NEO4J_AUTH=neo4j/neo4j