services:
  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/volume/data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/create_tables.sql