services:
  zookeeper:
    image: zookeeper:3.5.6
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
  
  pinot-controller:
    image: apachepinot/pinot:latest
    hostname: pinot-controller
    ports:
      - "9000:9000"
    volumes:
      - ./docker/volume/controller:/tmp/data/controller
    command: StartController -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
  
  pinot-broker:
    image: apachepinot/pinot:latest
    hostname: pinot-broker
    ports:
      - "8099:8099"
    command: StartBroker -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
      - pinot-controller
  
  pinot-server:
    image: apachepinot/pinot:latest
    hostname: pinot-server
    ports:
      - "8098:8098"
    volumes:
      - ./docker/volume/server:/tmp/data/server
    command: "StartServer -zkAddress zookeeper:2181"
    depends_on:
      - zookeeper
      - pinot-controller