services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongodb
            - MONGO_INITDB_ROOT_PASSWORD=mongodb
        volumes:
          - ./docker/volume/data:/var/lib/mongodb/data
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_AUTH_USERNAME=mongodb
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongodb
            - ME_CONFIG_MONGODB_URL=mongodb://mongodb:mongodb@mongodb:27017
