
# name or the intended use of these models
name: "dbt_airflow"
version: "1.0.0"
config-version: 2
require-dbt-version: [ ">=1.7.1", "<=1.7.7" ]

# This setting configures which "profile" dbt uses for this project.
profile: "trino"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"
  - "seeds"

models:
  dbt_airflow:
    +on_table_exists: drop
    dev:
      # +schema: mart
      +materialized: table # view, table, ephemeral, Incremental
