version: "3.7"

x-kafka-common: &kafka-common
  image: confluentinc/cp-kafka:7.2.1.arm64
  restart: on-failure
  healthcheck:
    test: curl --user superUser:superUser -fail --silent --insecure https://kafka1:8091/kafka/v3/clusters/ --output /dev/null || exit 1
    interval: 10s
    retries: 25
    start_period: 20s
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  depends_on:
    zookeeper:
      condition: service_started

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1.arm64
    restart: always
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      retries: 20
      interval: 10s
    volumes:
      - ./zookeeper/data:/kafka/data
      - ./zookeeper/datalog:/kafka/datalog
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    <<: *kafka-common
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
#      BOOTSTRAP_SERVERS: kafka1:9091, kafka2:9092, kafka3:9093

#  kafka2:
#    <<: *kafka-common
#    hostname: kafka2
#    container_name: kafka2
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9093"
#      BOOTSTRAP_SERVERS: kafka1:9091, kafka2:9092, kafka3:9093
#
#  kafka3:
#    <<: *kafka-common
#    hostname: kafka3
#    container_name: kafka3
#    ports:
#      - "9094:9092"
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9093
#      BOOTSTRAP_SERVERS: kafka1:9091, kafka2:9092, kafka3:9093
