version: "3.7"
services:
  redis-standalone:
    image: redis:7.0.2
    container_name: redis-test
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server
    ports:
      - "6379:6379"
