version: "3.7"
services:
    redis-search:
        container_name: redisgraph
        restart: always
        image: redislabs/redisgraph:2.8.20
        ports:
            - "6379:6379"
        volumes:
            - redis:/data/redis/

volumes:
    redis: